services:
  mysql_container:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=QuantumFinance
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-volume/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  mysql-data:
    driver: local